### ISSUE TITLE
Support of code for DMT method

### ISSUE THREAD

**Issue by rose-jinyang** [HiLab-git/SSL4MIS#15]
Hello
How are you?
Thanks for contributing to this project.
Could u support the code for DMT method (https://arxiv.org/pdf/2004.08514.pdf)?
Thanks

**Comment by Luoxd1996** [comment]
Hi Jinyang, Sorry，I don't want to implement it, you'd better implement DMT by yourself, I think it is easy. Best, Xiangde. Luo xd ***@***.*** 签名由 网易邮箱大师 定制 On 03/31/2021 22:26, rose-jinyang wrote: Hello How are you? Thanks for contributing to this project. Could u support the code for DMT method (https://arxiv.org/pdf/2004.08514.pdf)? Thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rose-jinyang** [comment]
Thanks for your reply.
In fact, I'm curious if the URPC method outperforms the DMT method.

**Comment by Luoxd1996** [comment]
Hi Jinyang,
I don't compare DMT with URPC as the DMT focus on natural images but the URPC is specific designed to deal with NPC task, so I don't know which one is better.
Best,
Xiangde.

**Comment by rose-jinyang** [comment]
Thanks
