### ISSUE TITLE
Support of code for the URPC method

### ISSUE THREAD

**Issue by rose-jinyang** [HiLab-git/SSL4MIS#16]
Hello
How are you?
Thanks for contributing to this project.
I can NOT find the code for the paper "Efficient Semi-Supervised Gross Target Volume of Nasopharyngeal Carcinoma Segmentation via Uncertainty Rectified Pyramid Consistency" (https://arxiv.org/pdf/2012.07042.pdf).
But the author of this paper said that the code is avaiable in this project.

![image](https://user-images.githubusercontent.com/47862419/113161861-59c56300-9271-11eb-91d5-53ba8ea0db2f.png)

How should I understand this?
Thanks

**Comment by Luoxd1996** [comment]
Hi， The 2D version is available now, in the code folder, the 3D version will be released upon the paper was accepted. Best, Xiangde. Luo xd ***@***.*** 签名由 网易邮箱大师 定制 On 03/31/2021 22:35, rose-jinyang wrote: Hello How are you? Thanks for contributing to this project. I can NOT find the code for the paper "Efficient Semi-Supervised Gross Target Volume of Nasopharyngeal Carcinoma Segmentation via Uncertainty Rectified Pyramid Consistency" (https://arxiv.org/pdf/2012.07042.pdf). But the author of this paper said that the code is released in this project. How should I understand this? Thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rose-jinyang** [comment]
Thanks for your reply.
